/**
 * Created by kenn on 16/7/4.
 */
//home
export * from '../apps/home/type'
export * from '../apps/user/type'
export * from '../apps/shop/type'
export * from '../apps/common/type'

export const CHECKED = 'CHECKED'
export const CHECKEDS = 'CHECKEDS'

export const WAITING = 'WAITING'

export const ERROR_CLEAN = 'ERROR_CLEAN'

//提示组件
export const SNACKBAR_OPEN = 'SNACKBAR_OPEN'

//短信验证码
export const PHONE_CODE = 'PHONE_CODE'
export const PHONE_GET_CODE = 'PHONE_GET_CODE'

export const CONFIRM_DIALOG_OPEN = 'CONFIRM_DIALOG_OPEN'
export const CONFIRM_DIALOG_CANCEL = 'CONFIRM_DIALOG_CANCEL'

//user
export const ACCOUNT_EXIST = 'ACCOUNT_EXIST'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN = 'USER_LOGIN'
export const USERADMIN_LOGIN = 'USERADMIN_LOGIN'
export const ADMIN_LOGIN = 'ADMIN_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_PHONE_NOEXIST = 'USER_PHONE_NOEXIST'
export const USER_EDIT = 'USER_EDIT'
export const USER_PASSWORD_EXIST = 'USER_PASSWORD_EXIST'
export const USER_EMAIL_NOEXIST = 'USER_EMAIL_NOEXIST'
export const USER_NAME_NOEXIST = 'USER_NAME_NOEXIST'

/**
 * 商品发布编辑
 */
export const GOODS_EDIT_SELECT_CATEGORY = 'GOODS_EDIT_SELECT_CATEGORY'
export const GOODS_EDIT_SELECT_TYPE = 'GOODS_EDIT_SELECT_TYPE'
//商品通用名称
export const GOODS_EDIT_NAME = 'GOODS_EDIT_NAME'
//商品编辑是的名称
export const GOODS_EDIT_INIT = 'GOODS_EDIT_INIT'
export const GOODS_EDIT_NAMES = 'GOODS_EDIT_NAMES'
export const GOODS_EDIT_JINGLE = 'GOODS_EDIT_JINGLE'
export const GOODS_EDIT_PRICE = 'GOODS_EDIT_PRICE'
export const GOODS_EDIT_COMMON_NAME = 'GOODS_EDIT_COMMON_NAME'
export const GOODS_EDIT_COMMON_TYPE = 'GOODS_EDIT_COMMON_TYPE'
export const GOODS_EDIT_COMMON_BRAND = 'GOODS_EDIT_COMMON_BRAND'
export const GOODS_EDIT_SPEC_INIT = 'GOODS_EDIT_SPEC_INIT'
export const GOODS_EDIT_SPEC_ADD = 'GOODS_EDIT_SPEC_ADD'
export const GOODS_EDIT_SPEC_REMOVE = 'GOODS_EDIT_SPEC_REMOVE'
export const GOODS_EDIT_SPEC_VALUE = 'GOODS_EDIT_SPEC_VALUE'
export const GOODS_EDIT_IMAGES_ADD = 'GOODS_EDIT_IMAGES_ADD'
export const GOODS_EDIT_MAIN_IMAGE = 'GOODS_EDIT_MAIN_IMAGE'
export const GOODS_EDIT_IMAGE_REMOVE = 'GOODS_EDIT_IMAGE_REMOVE'
export const GOODS_EDIT_IMAGE_REPLACE = 'GOODS_EDIT_IMAGE_REPLACE'
export const GOODS_EDIT_STORE_SERIAL = 'GOODS_EDIT_STORE_SERIAL'
export const GOODS_EDIT_STORE_TRANSPORT = 'GOODS_EDIT_STORE_TRANSPORT'
export const GOODS_EDIT_STORAGE = 'GOODS_EDIT_STORAGE'
export const GOODS_EDIT_STORAGE_SLARM = 'GOODS_EDIT_STORAGE_SLARM'

export const GOODS_EDIT_BODY_EDIT = 'GOODS_EDIT_BODY_EDIT'
export const GOODS_EDIT_BODY_ADD = 'GOODS_EDIT_BODY_ADD'
export const GOODS_EDIT_BODY_REMOVE = 'GOODS_EDIT_BODY_REMOVE'

export const GOODS_EDIT_SAVE = 'GOODS_EDIT_SAVE'

export const GOODS_DATAS_LOAD = 'GOODS_DATAS_LOAD'

//商品标签
export const GOODS_TAG_LOAD = 'GOODS_TAG_LOAD'
export const GOODS_TAG_SAVE = 'GOODS_TAG_SAVE'

/**
 * 地区
 */
export const AREA_LOAD = 'AREA_LOAD'
export const AREA_MULTI_LOAD = 'AREA_MULTI_LOAD'

/**
 * 分类
 */
export const CATEGORY_LOAD = 'CATEGORY_LOAD'

/**
 * 类型
 */
export const TYPES_LOAD = 'TYPES_LOAD'

/**
 * 品牌
 */
export const BRANDS_LOAD = 'BRANDS_LOAD'



