/**
 * Created by kenn on 16/7/17.
 */
export default {
    1: {
        GoodsCommonid: 1,
        GoodsJingle: "",
        GoodsName: 'iphone6 plus',
        Nrice: 6888,
        StoreId: 1,
        StoreName: '海牛',
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        BrandId: 1,
        GoodsSerial: 0,
        GoodsStorageAlarm: 0,
        GoodsClick: 0,
        GoodsSalenum: 0,
        GoodsCollect: 0,
        GoodsSpec: {
            1: {name: '颜色', value: {1: '金色'}},
            2: {name: '容量', value: {4: '64G'}},
        },
        GoodsStorage: 0,
        GoodsImage: [],
        GoodsState: 0,
        GoodsVerify: 0,
        GoodsAddtime: 0,
        GoodsEdittime: 0,
        Areaid_1: 0,
        Areaid_2: 0,
        ColorId: 0,
        GoodsFreight: 0, // '运费 0为免运费',
        EvaluationGoodStar: 0, // '好评星级'
        EvaluationCount: 0,//'评价数'
    },
    2: {
        GoodsCommonid: 1,
        GoodsJingle: "",
        GoodsName: 'iphone6 plus',
        Nrice: 6888,
        StoreId: 1,
        StoreName: '海牛',
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        BrandId: 1,
        GoodsSerial: 0,
        GoodsStorageAlarm: 0,
        GoodsClick: 0,
        GoodsSalenum: 0,
        GoodsCollect: 0,
        GoodsSpec: {
            1: {name: '颜色', value: { 2: '银色'}},
            2: {name: '容量', value: {4: '64G', }},
        },
        GoodsStorage: 0,
        GoodsImage: [],
        GoodsState: 0,
        GoodsVerify: 0,
        GoodsAddtime: 0,
        GoodsEdittime: 0,
        Areaid_1: 0,
        Areaid_2: 0,
        ColorId: 0,
        GoodsFreight: 0, // '运费 0为免运费',
        EvaluationGoodStar: 0, // '好评星级'
        EvaluationCount: 0,//'评价数'
    },
    3: {
        GoodsCommonid: 1,
        GoodsJingle: "",
        GoodsName: 'iphone6 plus',
        Nrice: 6888,
        StoreId: 1,
        StoreName: '海牛',
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        BrandId: 1,
        GoodsSerial: 0,
        GoodsStorageAlarm: 0,
        GoodsClick: 0,
        GoodsSalenum: 0,
        GoodsCollect: 0,
        GoodsSpec: {
            1: {name: '颜色', value: { 3: '灰色'}},
            2: {name: '容量', value: {4: '64G'}},
        },
        GoodsStorage: 0,
        GoodsImage: [],
        GoodsState: 0,
        GoodsVerify: 0,
        GoodsAddtime: 0,
        GoodsEdittime: 0,
        Areaid_1: 0,
        Areaid_2: 0,
        ColorId: 0,
        GoodsFreight: 0, // '运费 0为免运费',
        EvaluationGoodStar: 0, // '好评星级'
        EvaluationCount: 0,//'评价数'
    },
    4: {
        GoodsCommonid: 1,
        GoodsJingle: "",
        GoodsName: 'iphone6 plus',
        Nrice: 6888,
        StoreId: 1,
        StoreName: '海牛',
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        BrandId: 1,
        GoodsSerial: 0,
        GoodsStorageAlarm: 0,
        GoodsClick: 0,
        GoodsSalenum: 0,
        GoodsCollect: 0,
        GoodsSpec: {
            1: {name: '颜色', value: {1: '金色'}},
            2: {name: '容量', value: {5: '128G'}},
        },
        GoodsStorage: 0,
        GoodsImage: [],
        GoodsState: 0,
        GoodsVerify: 0,
        GoodsAddtime: 0,
        GoodsEdittime: 0,
        Areaid_1: 0,
        Areaid_2: 0,
        ColorId: 0,
        GoodsFreight: 0, // '运费 0为免运费',
        EvaluationGoodStar: 0, // '好评星级'
        EvaluationCount: 0,//'评价数'
    },
    5: {
        GoodsCommonid: 1,
        GoodsJingle: "",
        GoodsName: 'iphone6 plus',
        Nrice: 6888,
        StoreId: 1,
        StoreName: '海牛',
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        BrandId: 1,
        GoodsSerial: 0,
        GoodsStorageAlarm: 0,
        GoodsClick: 0,
        GoodsSalenum: 0,
        GoodsCollect: 0,
        GoodsSpec: {
            1: {name: '颜色', value: { 2: '银色'}},
            2: {name: '容量', value: { 5: '128G'}},
        },
        GoodsStorage: 0,
        GoodsImage: [],
        GoodsState: 0,
        GoodsVerify: 0,
        GoodsAddtime: 0,
        GoodsEdittime: 0,
        Areaid_1: 0,
        Areaid_2: 0,
        ColorId: 0,
        GoodsFreight: 0, // '运费 0为免运费',
        EvaluationGoodStar: 0, // '好评星级'
        EvaluationCount: 0,//'评价数'
    },
    6: {
        GoodsCommonid: 1,
        GoodsJingle: "",
        GoodsName: 'iphone6 plus',
        Nrice: 6888,
        StoreId: 1,
        StoreName: '海牛',
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        BrandId: 1,
        GoodsSerial: 0,
        GoodsStorageAlarm: 0,
        GoodsClick: 0,
        GoodsSalenum: 0,
        GoodsCollect: 0,
        GoodsSpec: {
            1: {name: '颜色', value: {3: '灰色'}},
            2: {name: '容量', value: { 5: '128G'}},
        },
        GoodsStorage: 0,
        GoodsImage: [],
        GoodsState: 0,
        GoodsVerify: 0,
        GoodsAddtime: 0,
        GoodsEdittime: 0,
        Areaid_1: 0,
        Areaid_2: 0,
        ColorId: 0,
        GoodsFreight: 0, // '运费 0为免运费',
        EvaluationGoodStar: 0, // '好评星级'
        EvaluationCount: 0,//'评价数'
    },
}