/**
 * Created by kenn on 16/7/17.
 */
export default {
    1: {
        GoodsName: '苹果ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        Spec: {
            1: {name: '颜色', value: {1: '金色', 2: '银色', 3: '灰色ddsdsdss'}},
            2: {name: '容量', value: {4: '64G', 5: '128G'}},
        },                     //'规格名称',
        //SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: [
            {type: 0, rows: 2,data:['商品名称：APPLEiPhone 6s', '商品编号：1856588', '商品毛重：420.00g', '商品产地：中国大陆', '热点：指纹识别，Apple Pay，金属机身，拍照神器', '系统：苹果（IOS）', '像素：1000-1600万']},
            'images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    2: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    3: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    5: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    4: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    6: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    7: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    8: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
    9: {
        GoodsName: 'ipnone6 plus',  //'商品名称'
        GoodsJingle: '唯一不同的是处处不同',            //'商品广告词'
        GcId1: 1,
        GcId2: 7,
        GcId3: 10,
        GcName: '',                 //'商品分类',
        StoreId: 1,
        StoreName: '海牛',
        SpecName: '',               //'规格名称',
        SpecValue: '',              //'规格值',
        BrandId: 1,                 //'品牌id',
        BrandName: 'apple',         //'品牌名称',
        GoodsImage: 'images/test/iphone6.jpg',             //'商品主图',
        GoodsState: 1,              //'商品状态 0下架，1正常，10违规（禁售）',
        GoodsStateremark: '',       //违规原因',
        GoodsVerify: 1,             //'商品审核 1通过，0未通过，10审核中',
        GoodsVerifyremark: '',      //'审核失败原因',
        GoodsLock: 0,               // tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '商品锁定 0未锁，1已锁',
        GoodsAddtime: 0,            // int(10) unsigned NOT NULL COMMENT '商品添加时间',
        GoodsSelltime: 0,           // int(10) unsigned NOT NULL COMMENT '上架时间',
        GoodsSpecname: '',          //'规格名称序列化（下标为规格id）',
        GoodsPrice: 6888,             //'商品价格',
        GoodsSerial: '',            //'商家编号',
        GoodsFreight: 0,            // decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '运费 0为免运费',
        Areaid_1: 1,                //int(10) unsigned NOT NULL COMMENT '一级地区id',
        Areaid_2: 1,                // int(10) unsigned NOT NULL COMMENT '二级地区id',
        GoodsStcids: '',            // varchar(255) NOT NULL DEFAULT '' COMMENT '店铺分类id 首尾用,隔开',
        GoodsBody: ['images/test/01.jpg','images/test/02.jpg','images/test/03.jpg','images/test/04.jpg','images/test/05.jpg','images/test/06.jpg','images/test/07.jpg','images/test/08.jpg',],              //'商品内容',
        GoodsImages: ['images/test/1.jpg','images/test/2.jpg','images/test/3.jpg','images/test/4.jpg','images/test/5.jpg','images/test/6.jpg','images/test/7.jpg','images/test/8.jpg',]
    },
}