export const SIMPLE_ALERT = 'SIMPLE_ALERT'


/**
 * 商户登录和信息管理
 */
export const STORE_LOGOUT = 'STORE_LOGOUT'
export const STORE_LOAD = 'STORE_LOAD'
export const STORE_LOGIN = 'STORE_LOGIN'
export const STORE_EDIT = 'STORE_EDIT'
export const STORE_STATIC = 'STORE_STATIC'

/**
 * 商户商品管理
 */
export const STORE_GOODS_COMMON_LOAD = 'STORE_GOODS_COMMON_LOAD'
export const STORE_GOODS_COMMON_ONLINE_LOAD = 'STORE_GOODS_COMMON_ONLINE_LOAD'
export const STORE_GOODS_COMMON_OFFLINE_LOAD = 'STORE_GOODS_COMMON_OFFLINE_LOAD'
export const STORE_GOODS_COMMON_SHOW = 'STORE_GOODS_COMMON_SHOW'
export const STORE_GOODS_COMMON_UNSHOW = 'STORE_GOODS_COMMON_UNSHOW'
export const STORE_GOODS_DELETE = 'STORE_GOODS_DELETE'

/**
 * 商户订单管理
 */
export const STORE_ORDERS_LOAD = 'STORE_ORDERS_LOAD'
export const STORE_ORDER_INFO = 'STORE_ORDER_INFO'
export const STORE_ORDER_CANCEL = 'STORE_ORDER_CANCEL'
export const STORE_ORDER_GOODS_LOAD = 'STORE_ORDER_GOODS_LOAD'
export const ORDER_SEND_LOAD = 'ORDER_SEND_LOAD'
export const ORDER_SEND_ADD = 'ORDER_SEND_ADD'
export const ORDER_SHIPPINGFEE_EDIT = 'ORDER_SHIPPINGFEE_EDIT'

/**
 * 商户物流管理
 */
export const STORE_TRANSPORT_LOAD = 'STORE_TRANSPORT_LOAD'
export const STORE_TRANSPORT_ADD = 'STORE_TRANSPORT_ADD'
export const STORE_TRANSPORT_EDIT = 'STORE_TRANSPORT_EDIT'
export const STORE_TRANSPORT_EDIT_SAVE = 'STORE_TRANSPORT_EDIT_SAVE'
export const STORE_TRANSPORT_EDITABLE = 'STORE_TRANSPORT_EDITABLE'
export const STORE_TRANSPORT_EDIT_CANCEL = 'STORE_TRANSPORT_EDIT_CANCEL'
export const STORE_TRANSPORT_DELETE = 'STORE_TRANSPORT_DELETE'
export const STORE_TRANSPORT_AREA_CHANGE = 'STORE_TRANSPORT_AREA_CHANGE'
export const STORE_TRANSPORT_EXTENDS_ADD = 'STORE_TRANSPORT_EXTENDS_ADD'
export const STORE_TRANSPORT_EXTENDS_EDITABLE = 'STORE_TRANSPORT_EXTENDS_EDITABLE'
export const STORE_TRANSPORT_EXTENDS_EDIT = 'STORE_TRANSPORT_EXTENDS_EDIT'
export const STORE_TRANSPORT_EXTENDS_EDIT_CANCEL = 'STORE_TRANSPORT_EXTENDS_EDIT_CANCEL'
export const STORE_TRANSPORT_EXTENDS_EDIT_AREA_SAVE = 'STORE_TRANSPORT_EXTENDS_EDIT_AREA_SAVE'
export const STORE_TRANSPORT_EXTENDS_SAVE = 'STORE_TRANSPORT_EXTENDS_SAVE'
export const STORE_TRANSPORT_EXTENDS_DELETE = 'STORE_TRANSPORT_EXTENDS_DELETE'

export const EXPRESS_LOAD = 'EXPRESS_LOAD'
export const STORE_EXTEND_LOAD = 'STORE_EXTEND_LOAD'
export const STORE_EXTEND_ADD = 'STORE_EXTEND_ADD'
export const STORE_FREE_FREIGHT_SAVE = 'STORE_FREE_FREIGHT_SAVE'
export const STORE_FREE_FREIGHT_CHANGE = 'STORE_FREE_FREIGHT_CHANGE'



/**
 * 发货地址管理
 * @type {string}
 */
export const DADDRESS_LOAD = 'DADDRESS_LOAD'                //发货地址载入
export const DADDRESS_SET_DEFAULT = 'DADDRESS_SET_DEFAULT'  //设置默认发货地址
export const DADDRESS_DELETE_BY_ID = 'DADDRESS_DELETE_BY_ID'    //根据ID删除发货地址
export const DADDRESS_EDIT = 'DADDRESS_EDIT'            //编辑发货地址
export const DADDRESS_ADD_SAVE = 'DADDRESS_ADD_SAVE'    //保存发货地址
export const DADDRESS_EDIT_SAVE = 'DADDRESS_EDIT_SAVE'  //更新发货地址

/**
 * 发货区域
 * @type {string}
 */
export const STORE_OFFPAY_AREA_LOAD = 'STORE_OFFPAY_AREA_LOAD'  //货到付款地区
export const STORE_OFFPAY_AREA_SAVE = 'STORE_OFFPAY_AREA_SAVE'  //保存货到付款地区
export const STORE_OFFPAY_AREA_CHANGE = 'STORE_OFFPAY_AREA_CHANGE'  //更改货到付款地区

/**
 * 退货
 * @type {string}
 */
export const STORE_REFUND_RETURN_LOAD = 'STORE_REFUND_RETURN_LOAD'

/**
 * 结算管理
 * @type {string}
 */
export const STORE_ORDER_BILL_LOAD = 'STORE_ORDER_BILL_LOAD'



